/** Mapeamento código da moeda → país/região em português */
export const PAISES: Record<string, string> = {
  AED: 'Emirados Árabes',
  AFN: 'Afeganistão',
  ALL: 'Albânia',
  AMD: 'Armênia',
  ANG: 'Antilhas Holandesas',
  AOA: 'Angola',
  ARS: 'Argentina',
  AUD: 'Austrália',
  AWG: 'Aruba',
  AZN: 'Azerbaijão',
  BAM: 'Bósnia',
  BBD: 'Barbados',
  BDT: 'Bangladesh',
  BGN: 'Bulgária',
  BHD: 'Bahrein',
  BIF: 'Burundi',
  BMD: 'Bermudas',
  BND: 'Brunei',
  BOB: 'Bolívia',
  BRL: 'Brasil',
  BSD: 'Bahamas',
  BTC: 'Bitcoin',
  BTN: 'Butão',
  BWP: 'Botsuana',
  BYN: 'Bielorrússia',
  BZD: 'Belize',
  CAD: 'Canadá',
  CDF: 'Congo',
  CHF: 'Suíça',
  CLP: 'Chile',
  CNH: 'China',
  CNY: 'China',
  COP: 'Colômbia',
  CRC: 'Costa Rica',
  CUP: 'Cuba',
  CVE: 'Cabo Verde',
  CZK: 'República Tcheca',
  DJF: 'Djibuti',
  DKK: 'Dinamarca',
  DOP: 'República Dominicana',
  DZD: 'Argélia',
  EGP: 'Egito',
  ETB: 'Etiópia',
  EUR: 'União Europeia',
  FJD: 'Fiji',
  GBP: 'Reino Unido',
  GEL: 'Geórgia',
  GHS: 'Gana',
  GMD: 'Gâmbia',
  GNF: 'Guiné',
  GTQ: 'Guatemala',
  HKD: 'Hong Kong',
  HNL: 'Honduras',
  HRK: 'Croácia',
  HTG: 'Haiti',
  HUF: 'Hungria',
  IDR: 'Indonésia',
  ILS: 'Israel',
  INR: 'Índia',
  IQD: 'Iraque',
  IRR: 'Irã',
  ISK: 'Islândia',
  JMD: 'Jamaica',
  JOD: 'Jordânia',
  JPY: 'Japão',
  KES: 'Quênia',
  KGS: 'Quirguistão',
  KHR: 'Camboja',
  KMF: 'Comores',
  KRW: 'Coreia do Sul',
  KWD: 'Kuwait',
  KZT: 'Cazaquistão',
  LAK: 'Laos',
  LBP: 'Líbano',
  LKR: 'Sri Lanka',
  LYD: 'Líbia',
  MAD: 'Marrocos',
  MDL: 'Moldávia',
  MGA: 'Madagascar',
  MKD: 'Macedônia',
  MMK: 'Mianmar',
  MNT: 'Mongólia',
  MOP: 'Macau',
  MUR: 'Maurício',
  MVR: 'Maldivas',
  MWK: 'Malawi',
  MXN: 'México',
  MYR: 'Malásia',
  MZN: 'Moçambique',
  NAD: 'Namíbia',
  NGN: 'Nigéria',
  NIO: 'Nicarágua',
  NOK: 'Noruega',
  NPR: 'Nepal',
  NZD: 'Nova Zelândia',
  OMR: 'Omã',
  PAB: 'Panamá',
  PEN: 'Peru',
  PGK: 'Papua Nova Guiné',
  PHP: 'Filipinas',
  PKR: 'Paquistão',
  PLN: 'Polônia',
  PYG: 'Paraguai',
  QAR: 'Catar',
  RON: 'Romênia',
  RSD: 'Sérvia',
  RUB: 'Rússia',
  RWF: 'Ruanda',
  SAR: 'Arábia Saudita',
  SCR: 'Seychelles',
  SDG: 'Sudão',
  SEK: 'Suécia',
  SGD: 'Singapura',
  SLL: 'Serra Leoa',
  SOS: 'Somália',
  SSP: 'Sudão do Sul',
  STD: 'São Tomé',
  SVC: 'El Salvador',
  SYP: 'Síria',
  SZL: 'Essuatíni',
  THB: 'Tailândia',
  TJS: 'Tajiquistão',
  TMT: 'Turcomenistão',
  TND: 'Tunísia',
  TRY: 'Turquia',
  TTD: 'Trinidad e Tobago',
  TWD: 'Taiwan',
  TZS: 'Tanzânia',
  UAH: 'Ucrânia',
  UGX: 'Uganda',
  USD: 'Estados Unidos',
  UYU: 'Uruguai',
  UZS: 'Uzbequistão',
  VES: 'Venezuela',
  VND: 'Vietnã',
  VUV: 'Vanuatu',
  XAF: 'África Central',
  XCD: 'Caribe Oriental',
  XOF: 'África Ocidental',
  XPF: 'Polinésia Francesa',
  YER: 'Iêmen',
  ZAR: 'África do Sul',
  ZMW: 'Zâmbia',
  ZWL: 'Zimbábue',
};

export function obterPais(code: string, descricao: string): string {
  return PAISES[code] ?? descricao;
}
